descriptor-schema-version: "2.7"
info:
  name: container_b
  version: latest
app:
  cpuarch: x86_64
  env:
    GPG_KEY: E3FF2839C048B25C084DEBE9B26995E310250568
    LANG: C.UTF-8
    PATH: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    PYTHON_GET_PIP_SHA256: e235c437e5c7d7524fbce3880ca39b917a73dc565e0c813465b7a7a329bb279a
    PYTHON_GET_PIP_URL: https://github.com/pypa/get-pip/raw/38e54e5de07c66e875c11a1ebbdb938854625dd8/public/get-pip.py
    PYTHON_PIP_VERSION: 22.0.4
    PYTHON_SETUPTOOLS_VERSION: 57.5.0
    PYTHON_VERSION: 3.8.13
  resources:
    network:
    - interface-name: eth0
      ports:
        tcp:
        - "80"
    profile: c1.tiny
  startup:
    rootfs: rootfs.tar
    target:
    - python3
    - webserver.py
  type: docker
